services:
  servidor:
    build:
      context: ../
      dockerfile: docker-debug/servidor.dockerfile
      tags: 
        - "servidor"
    networks:
      - network-ra
    deploy:
      mode: replicated
      endpoint_mode: vip
      replicas: 5

  cliente:
    build:
      context: ../
      dockerfile: docker-debug/cliente.dockerfile
      tags:
        - "cliente"
    networks:
      - network-ra
    depends_on:
      - servidor
    deploy:
      mode: replicated
      replicas: 1
    entrypoint:
      - /bin/bash
      - /proyecto/docker/cliente.sh

networks:
  network-ra:
    ipam:
      config:
        - subnet: "172.20.100.0/24"
